export const TALENT_THEMES = [
  // Executing Domain
  "Consistent Producer", "Shift Coordinator", "Mission-Driven", "Standardized Care", 
  "Risk Mitigator", "Clinical Precision", "Target-Oriented", "Ultimate Owner", "Crisis Fixer",
  
  // Influencing Domain
  "Momentum Builder", "Direct Leader", "Staff Storyteller", "Performance Driver", 
  "Excellence Seeker", "Confident Clinician", "Legacy Maker", "Community Connector",
  
  // Relationship Domain
  "Fluid Responder", "Holistic Thinker", "Staff Mentor", "Compassionate Sensor", 
  "Peace Mediator", "Team Integrator", "Person-Centered", "Morale Booster", "Direct Confidant",
  
  // Strategic Domain
  "Data Validator", "Historical Expert", "Future-Care Visionary", "Creative Strategist", 
  "Resource Collector", "Deep Contemplator", "Clinical Scholar", "Pathway Mapper"
];

export const FORCED_CHOICE_QUESTIONS = [
  { id: 1, optionA: { text: "I love imagining the future of healthcare technology.", theme: "Future-Care Visionary" }, optionB: { text: "I love ensuring every chart is 100% compliant today.", theme: "Clinical Precision" } },
  { id: 2, optionA: { text: "I prefer to work with one patient deeply for a long time.", theme: "Direct Confidant" }, optionB: { text: "I enjoy meeting new residents and their families.", theme: "Community Connector" } },
  { id: 3, optionA: { text: "I am at my best when the floor is chaotic and fast-paced.", theme: "Fluid Responder" }, optionB: { text: "I am at my best when I have a rigid, set routine.", theme: "Clinical Precision" } },
  { id: 4, optionA: { text: "I want to be recognized as the best nurse in the building.", theme: "Legacy Maker" }, optionB: { text: "I want to be known as the most helpful teammate.", theme: "Team Integrator" } },
  { id: 5, optionA: { text: "I look at past survey results to fix current problems.", theme: "Historical Expert" }, optionB: { text: "I look at current data to predict next year's trends.", theme: "Data Validator" } },
  { id: 6, optionA: { text: "I naturally take charge during a medical emergency.", theme: "Direct Leader" }, optionB: { text: "I prefer to support the person who is in charge.", theme: "Team Integrator" } },
  { id: 7, optionA: { text: "I see each resident as a unique individual with a story.", theme: "Person-Centered" }, optionB: { text: "I see each resident as a clinical case to be managed.", theme: "Consistent Producer" } },
  { id: 8, optionA: { text: "I am driven to hit every single metric on my scorecard.", theme: "Performance Driver" }, optionB: { text: "I am driven to make sure the staff feels happy today.", theme: "Morale Booster" } },
  { id: 9, optionA: { text: "I need time alone to think through a difficult diagnosis.", theme: "Deep Contemplator" }, optionB: { text: "I need to talk through a diagnosis with my coworkers.", theme: "Staff Storyteller" } },
  { id: 10, optionA: { text: "I am great at finding the 'shortcuts' to get work done.", theme: "Pathway Mapper" }, optionB: { text: "I never take shortcuts; I follow every policy exactly.", theme: "Standardized Care" } },
  { id: 11, optionA: { text: "I feel the physical pain and emotions of my residents.", theme: "Compassionate Sensor" }, optionB: { text: "I stay emotionally detached to remain professional.", theme: "Risk Mitigator" } },
  { id: 12, optionA: { text: "I enjoy teaching new CNAs how to improve their skills.", theme: "Staff Mentor" }, optionB: { text: "I prefer to do the work myself so I know it's done right.", theme: "Ultimate Owner" } },
  { id: 13, optionA: { text: "I love having a 'to-do' list and checking everything off.", theme: "Consistent Producer" }, optionB: { text: "I love coming up with new ideas for activities.", theme: "Creative Strategist" } },
  { id: 14, optionA: { text: "I speak up immediately if I see a safety violation.", theme: "Direct Leader" }, optionB: { text: "I try to resolve safety issues quietly and gently.", theme: "Peace Mediator" } },
  { id: 15, optionA: { text: "I am fascinated by the science and research of care.", theme: "Clinical Scholar" }, optionB: { text: "I am fascinated by the personal lives of my residents.", theme: "Direct Confidant" } },
  { id: 16, optionA: { text: "I want my work to leave a lasting impact on the facility.", theme: "Legacy Maker" }, optionB: { text: "I just want to do my job well and go home to my family.", theme: "Consistent Producer" } },
  { id: 17, optionA: { text: "I can easily spot the hidden talents in my coworkers.", theme: "Staff Mentor" }, optionB: { text: "I can easily spot the hidden risks on a patient floor.", theme: "Risk Mitigator" } },
  { id: 18, optionA: { text: "I am known for being the 'calm in the storm.'", theme: "Fluid Responder" }, optionB: { text: "I am known for being the 'voice of reason and logic.'", theme: "Data Validator" } },
  { id: 19, optionA: { text: "I prefer to have 5-6 tasks going at the exact same time.", theme: "Shift Coordinator" }, optionB: { text: "I prefer to focus on one single task until it is perfect.", theme: "Target-Oriented" } },
  { id: 20, optionA: { text: "I believe everything happens for a spiritual reason.", theme: "Holistic Thinker" }, optionB: { text: "I believe everything happens for a clinical/logical reason.", theme: "Data Validator" } },
  { id: 21, optionA: { text: "I prefer a shift where every protocol is followed perfectly.", theme: "Clinical Precision" }, optionB: { text: "I prefer a shift where I can improvise and react to changes.", theme: "Fluid Responder" } },
  { id: 22, optionA: { text: "I want my name to be associated with big facility improvements.", theme: "Legacy Maker" }, optionB: { text: "I want to be the one person a resident trusts with their secrets.", theme: "Direct Confidant" } },
  { id: 23, optionA: { text: "I need to see the clinical research before changing my routine.", theme: "Data Validator" }, optionB: { text: "I change my routine based on how the resident is feeling.", theme: "Compassionate Sensor" } },
  { id: 24, optionA: { text: "I am willing to be unpopular if it means keeping the floor safe.", theme: "Direct Leader" }, optionB: { text: "I am willing to compromise to keep the team from arguing.", theme: "Peace Mediator" } },
  { id: 25, optionA: { text: "I love brainstorming new ways to keep residents engaged.", theme: "Creative Strategist" }, optionB: { text: "I love focusing on one complex task until it is error-free.", theme: "Target-Oriented" } },
  { id: 26, optionA: { text: "My success is measured by how much my team grows.", theme: "Staff Mentor" }, optionB: { text: "My success is measured by how much work I get done.", theme: "Consistent Producer" } },
  { id: 27, optionA: { text: "I am always thinking about where this facility will be in 2 years.", theme: "Future-Care Visionary" }, optionB: { text: "I am always thinking about what we can learn from past surveys.", theme: "Historical Expert" } },
  { id: 28, optionA: { text: "I am naturally cautious and look for what might go wrong.", theme: "Risk Mitigator" }, optionB: { text: "I am naturally bold and want to start new projects today.", theme: "Momentum Builder" } },
  { id: 29, optionA: { text: "I make sure the quietest staff member is included in decisions.", theme: "Team Integrator" }, optionB: { text: "I focus on the high-performers who help us hit our metrics.", theme: "Performance Driver" } },
  { id: 30, optionA: { text: "I read medical journals to stay at the top of my field.", theme: "Clinical Scholar" }, optionB: { text: "I look for ways to make the breakroom a happier place.", theme: "Morale Booster" } },
  { id: 31, optionA: { text: "I thrive when following a strict, unvarying medication protocol.", theme: "Clinical Precision" }, optionB: { text: "I thrive when I can invent new ways to engage residents.", theme: "Creative Strategist" } },
  { id: 32, optionA: { text: "I feel best when I’ve completed a massive amount of documentation.", theme: "Consistent Producer" }, optionB: { text: "I feel best when I’ve helped a new CNA learn a new skill.", theme: "Staff Mentor" } },
  { id: 33, optionA: { text: "I am naturally inclined to spot what might go wrong during a shift.", theme: "Risk Mitigator" }, optionB: { text: "I am naturally inclined to trust my instincts and move forward.", theme: "Confidence Clinician" } },
  { id: 34, optionA: { text: "I make decisions based on what the charts and numbers tell me.", theme: "Data Validator" }, optionB: { text: "I make decisions based on the emotional energy in the room.", theme: "Compassionate Sensor" } },
  { id: 35, optionA: { text: "I want to be known as the most significant leader in the building.", theme: "Legacy Maker" }, optionB: { text: "I want to be known as the most ethical person in the building.", theme: "Mission-Driven" } },
  { id: 36, optionA: { text: "I can work for hours on one task without getting distracted.", theme: "Target-Oriented" }, optionB: { text: "I enjoy juggling 10 different staffing issues at the same time.", theme: "Shift Coordinator" } },
  { id: 37, optionA: { text: "I look at our previous survey deficiencies to plan for today.", theme: "Historical Expert" }, optionB: { text: "I look at new industry trends to plan for where we are going.", theme: "Future-Care Visionary" } },
  { id: 38, optionA: { text: "I treat every resident exactly the same to ensure total fairness.", theme: "Standardized Care" }, optionB: { text: "I treat every resident differently based on their unique personality.", theme: "Person-Centered" } },
  { id: 39, optionA: { text: "I enjoy being the one who makes the final call in a crisis.", theme: "Direct Leader" }, optionB: { text: "I enjoy being the one who brings a heated argument to a close.", theme: "Peace Mediator" } },
  { id: 40, optionA: { text: "I feel a personal failure if a single task on my shift is missed.", theme: "Ultimate Owner" }, optionB: { text: "I accept that shifts are chaotic and I just roll with the changes.", theme: "Fluid Responder" } },
  { id: 41, optionA: { text: "I spend my breaks reading up on new clinical certifications.", theme: "Clinical Scholar" }, optionB: { text: "I spend my breaks checking in on how my coworkers are doing.", theme: "Morale Booster" } },
  { id: 42, optionA: { text: "I love the thrill of 'winning over' a difficult new family member.", theme: "Community Connector" }, optionB: { text: "I love the comfort of a long-term bond with a regular resident.", theme: "Direct Confidant" } },
  { id: 43, optionA: { text: "I want to start the new wound-care initiative this morning.", theme: "Momentum Builder" }, optionB: { text: "I want to spend the morning thinking through why the initiative works.", theme: "Deep Contemplator" } },
  { id: 44, optionA: { text: "I keep a physical or digital folder of helpful tips for the floor.", theme: "Resource Collector" }, optionB: { text: "I prefer to come up with my own original ideas for the floor.", theme: "Creative Strategist" } },
  { id: 45, optionA: { text: "I am great at finding the fastest way to get through a med-pass.", theme: "Pathway Mapper" }, optionB: { text: "I am great at following every single step of a med-pass perfectly.", theme: "Clinical Precision" } },
  { id: 46, optionA: { text: "I make sure the 'quiet ones' on the team have a voice.", theme: "Team Integrator" }, optionB: { text: "I push the 'high performers' to keep our facility metrics high.", theme: "Performance Driver" } },
  { id: 47, optionA: { text: "I believe my work as a caregiver is part of a larger spiritual plan.", theme: "Holistic Thinker" }, optionB: { text: "I believe my work is about getting the job done efficiently.", theme: "Consistent Producer" } },
  { id: 48, optionA: { text: "I am frustrated by 'average' care; I want it to be 5-star.", theme: "Excellence Seeker" }, optionB: { text: "I am frustrated by conflict; I want everyone to get along.", theme: "Harmony" } },
  { id: 49, optionA: { text: "I need to see the logic behind a new facility policy.", theme: "Analytical" }, optionB: { text: "I am ready to implement a new policy as soon as it's announced.", theme: "Activator" } },
  { id: 50, optionA: { text: "I am very private and careful about what I share with coworkers.", theme: "Deliberative" }, optionB: { text: "I am an open book and love sharing stories to build the team.", theme: "Communication" } },
  { id: 51, optionA: { text: "I am most effective when I can improvise the best route to a goal.", theme: "Pathway Mapper" }, optionB: { text: "I am most effective when I follow the exact same route every time.", theme: "Standardized Care" } },
  { id: 52, optionA: { text: "I prioritize the unique history and quirks of a specific resident.", theme: "Person-Centered" }, optionB: { text: "I prioritize the clinical data and vital signs of a specific resident.", theme: "Data Validator" } },
  { id: 53, optionA: { text: "I am comfortable being the 'boss' and telling others what to do.", theme: "Direct Leader" }, optionB: { text: "I prefer being a 'coach' who helps others perform better.", theme: "Excellence Seeker" } },
  { id: 54, optionA: { text: "I naturally focus on preventing the worst-case scenario.", theme: "Risk Mitigator" }, optionB: { text: "I naturally focus on achieving the best-case scenario.", theme: "Future-Care Visionary" } },
  { id: 55, optionA: { text: "I love brainstorming five different ways to solve a staffing issue.", theme: "Creative Strategist" }, optionB: { text: "I just want the most proven, reliable way to solve it so I can move on.", theme: "Consistent Producer" } },
  { id: 56, optionA: { text: "I feel successful when my trainee gets a promotion.", theme: "Staff Mentor" }, optionB: { text: "I feel successful when our wing hits its monthly quality targets.", theme: "Performance Driver" } },
  { id: 57, optionA: { text: "I need quiet time to mentally 'process' the day’s events.", theme: "Deep Contemplator" }, optionB: { text: "I process the day by talking through events with my coworkers.", theme: "Staff Storyteller" } },
  { id: 58, optionA: { text: "I can 'feel' the mood of a resident as soon as I enter their room.", theme: "Compassionate Sensor" }, optionB: { text: "I 'check' the safety of the room as soon as I enter it.", theme: "Clinical Precision" } },
  { id: 59, optionA: { text: "I feel a personal burden if a coworker misses a task on my shift.", theme: "Ultimate Owner" }, optionB: { text: "I try to keep the peace and not make a big deal of missed tasks.", theme: "Peace Mediator" } },
  { id: 60, optionA: { text: "I want to be known as a high-achiever who stands out.", theme: "Legacy Maker" }, optionB: { text: "I want to be known as a reliable team player who fits in.", theme: "Team Integrator" } },
  { id: 61, optionA: { text: "I am frustrated by slow decision-making in the facility.", theme: "Momentum Builder" }, optionB: { text: "I am frustrated when we ignore the facility's past mistakes.", theme: "Historical Expert" } },
  { id: 62, optionA: { text: "I value being the most 'knowledgeable' person on the floor.", theme: "Clinical Scholar" }, optionB: { text: "I value being the most 'trusted' person on the floor.", theme: "Direct Confidant" } },
  { id: 63, optionA: { text: "I enjoy the puzzle of re-organizing a chaotic schedule.", theme: "Shift Coordinator" }, optionB: { text: "I enjoy the focus of completing one single, difficult project.", theme: "Target-Oriented" } },
  { id: 64, optionA: { text: "I see the 'invisible threads' that connect us all as a team.", theme: "Holistic Thinker" }, optionB: { text: "I see the logical steps that make us efficient as a team.", theme: "Analytical" } },
  { id: 65, optionA: { text: "I prioritize the happiness and energy level of the staff.", theme: "Morale Booster" }, optionB: { text: "I prioritize the accuracy and safety of the clinical work.", theme: "Clinical Precision" } },
  { id: 66, optionA: { text: "I love finding new tools and articles to share with everyone.", theme: "Resource Collector" }, optionB: { text: "I love creating my own new tools and methods from scratch.", theme: "Creative Strategist" } },
  { id: 67, optionA: { text: "I push for a decision to be made quickly.", theme: "Direct Leader" }, optionB: { text: "I prefer to wait and think deeply before a decision is made.", theme: "Deep Contemplator" } },
  { id: 68, optionA: { text: "My energy comes from having a huge 'to-do' list.", theme: "Consistent Producer" }, optionB: { text: "My energy comes from imagining what our facility could become.", theme: "Future-Care Visionary" } },
  { id: 69, optionA: { text: "I love the challenge of 'breaking the ice' with new families.", theme: "Community Connector" }, optionB: { text: "I love the comfort of a 1-on-1 bond with a long-term coworker.", theme: "Direct Confidant" } },
  { id: 70, optionA: { text: "I thrive on 'winging it' when things go wrong.", theme: "Fluid Responder" }, optionB: { text: "I thrive on having a 'Plan B' ready for when things go wrong.", theme: "Risk Mitigator" } },
  { id: 71, optionA: { text: "I am obsessed with turning 'good' care into 'great' care.", theme: "Excellence Seeker" }, optionB: { text: "I am obsessed with getting the 'good' care done on time.", theme: "Consistent Producer" } },
  { id: 72, optionA: { text: "I am known for being fair and treating everyone equally.", theme: "Standardized Care" }, optionB: { text: "I am known for noticing what makes everyone different.", theme: "Person-Centered" } },
  { id: 73, optionA: { text: "I learn best by 'doing' and jumping right in.", theme: "Activator" }, optionB: { text: "I learn best by 'studying' and reading the manual first.", theme: "Learner" } },
  { id: 74, optionA: { text: "I want to work on projects that get noticed by leadership.", theme: "Significance" }, optionB: { text: "I want to work on projects that help the team get along better.", theme: "Harmony" } },
  { id: 75, optionA: { text: "I dislike it when my routine is interrupted by small talk.", theme: "Target-Oriented" }, optionB: { text: "I love it when coworkers stop to share a laugh or a positive story.", theme: "Positivity" } },
  { id: 76, optionA: { text: "I feel most productive when I have a heavy patient load.", theme: "Consistent Producer" }, optionB: { text: "I feel most productive when I have time to think about one case.", theme: "Deep Contemplator" } },
  { id: 77, optionA: { text: "I want my facility to be famous for its high standards.", theme: "Legacy Maker" }, optionB: { text: "I want my facility to be famous for its peaceful atmosphere.", theme: "Harmony" } },
  { id: 78, optionA: { text: "I am naturally suspicious of new, untested care methods.", theme: "Risk Mitigator" }, optionB: { text: "I am naturally excited to try new care methods immediately.", theme: "Activator" } },
  { id: 79, optionA: { text: "I rely on objective facts to judge a staff member's work.", theme: "Data Validator" }, optionB: { text: "I rely on a person's potential to judge their work.", theme: "Staff Mentor" } },
  { id: 80, optionA: { text: "I am comfortable giving direct, blunt feedback to peers.", theme: "Direct Leader" }, optionB: { text: "I soften my feedback to protect people’s feelings.", theme: "Compassionate Sensor" } },
  { id: 81, optionA: { text: "I prefer to finish my charting before helping others.", theme: "Target-Oriented" }, optionB: { text: "I will stop my charting to help a coworker who looks busy.", theme: "Team Integrator" } },
  { id: 82, optionA: { text: "I love finding a 'workaround' for a difficult problem.", theme: "Creative Strategist" }, optionB: { text: "I believe 'workarounds' are dangerous and follow policy.", theme: "Standardized Care" } },
  { id: 83, optionA: { text: "I like being the person who manages the daily 'chaos.'", theme: "Shift Coordinator" }, optionB: { text: "I like being the person who designs the 'long-term' strategy.", theme: "Pathway Mapper" } },
  { id: 84, optionA: { text: "I am inspired by the technology we will use in 10 years.", theme: "Future-Care Visionary" }, optionB: { text: "I am inspired by the traditions and legacy of our facility.", theme: "Historical Expert" } },
  { id: 85, optionA: { text: "I want to see my wing's metrics on a public dashboard.", theme: "Performance Driver" }, optionB: { text: "I prefer to keep my performance and relationships private.", theme: "Direct Confidant" } },
  { id: 86, optionA: { text: "I am often told my standards for care are 'too high.'", theme: "Excellence Seeker" }, optionB: { text: "I am often told I am a 'workhorse' who gets a lot done.", theme: "Consistent Producer" } },
  { id: 87, optionA: { text: "I enjoy being the 'subject matter expert' on the floor.", theme: "Clinical Scholar" }, optionB: { text: "I enjoy being the 'most liked' person on the floor.", theme: "Community Connector" } },
  { id: 88, optionA: { text: "I believe a resident's spirit is as important as their vitals.", theme: "Holistic Thinker" }, optionB: { text: "I believe clinical vitals are the only true measure of health.", theme: "Clinical Precision" } },
  { id: 89, optionA: { text: "I find it hard to delegate tasks because I'm responsible.", theme: "Ultimate Owner" }, optionB: { text: "I find it easy to delegate and go with the flow of the shift.", theme: "Fluid Responder" } },
  { id: 90, optionA: { text: "I love to research 'best practices' in my spare time.", theme: "Resource Collector" }, optionB: { text: "I love to brainstorm my own 'best practices.'", theme: "Creative Strategist" } },
  { id: 91, optionA: { text: "I am impatient with long staff meetings.", theme: "Momentum Builder" }, optionB: { text: "I value long meetings if I am learning something new.", theme: "Learner" } },
  { id: 92, optionA: { text: "I believe a happy staff leads to healthy residents.", theme: "Morale Booster" }, optionB: { text: "I believe high clinical standards lead to healthy residents.", theme: "Performance Driver" } },
  { id: 93, optionA: { text: "I use stories and metaphors to explain care plans.", theme: "Communication" }, optionB: { text: "I use data and logic to explain care plans.", theme: "Analytical" } },
  { id: 94, optionA: { text: "I rarely look for validation from my supervisor.", theme: "Self-Assurance" }, optionB: { text: "I am highly motivated when my supervisor praises me.", theme: "Significance" } },
  { id: 95, optionA: { text: "I am very careful about who I trust on the team.", theme: "Deliberative" }, optionB: { text: "I trust my close teammates implicitly and share everything.", theme: "Relator" } },
  { id: 96, optionA: { text: "I am very aware of the staff members who feel ignored.", theme: "Includer" }, optionB: { text: "I am very aware of who is the most powerful in the room.", theme: "Command" } },
  { id: 97, optionA: { text: "I am at my best when I have to 'wing it.'", theme: "Adaptability" }, optionB: { text: "I am at my best when the plan goes exactly as scheduled.", theme: "Discipline" } },
  { id: 98, optionA: { text: "I am energized by a facility that has many problems to fix.", theme: "Restorative" }, optionB: { text: "I am energized by a facility that is already performing well.", theme: "Maximizer" } },
  { id: 99, optionA: { text: "I see connections between unrelated healthcare ideas.", theme: "Ideation" }, optionB: { text: "I see the one straight line to the goal and ignore everything else.", theme: "Focus" } },
  { id: 100, optionA: { text: "I notice the specific things that motivate each coworker.", theme: "Individualization" }, optionB: { text: "I expect everyone to be motivated by the same mission.", theme: "Belief" } },
  { id: 101, optionA: { text: "I quickly see the best way through a complex discharge.", theme: "Pathway Mapper" }, optionB: { text: "I want to study every detail of the discharge clinicals.", theme: "Clinical Scholar" } },
  { id: 102, optionA: { text: "I am energized by a fast-paced 'to-do' list.", theme: "Consistent Producer" }, optionB: { text: "I am energized by deep conversations with residents.", theme: "Direct Confidant" } },
  { id: 103, optionA: { text: "I can reorganize the floor when everyone is sick.", theme: "Shift Coordinator" }, optionB: { text: "I just focus on working twice as hard to get it done.", theme: "Consistent Producer" } },
  { id: 104, optionA: { text: "I want to lead a project that gets the facility an award.", theme: "Legacy Maker" }, optionB: { text: "I want to help a struggling CNA become a superstar.", theme: "Staff Mentor" } },
  { id: 105, optionA: { text: "I am the person who double-checks every med-label.", theme: "Risk Mitigator" }, optionB: { text: "I am the person who gets the shift moving at a fast pace.", theme: "Momentum Builder" } },
  { id: 106, optionA: { text: "I notice when a resident’s room layout affects their mood.", theme: "Person-Centered" }, optionB: { text: "I notice new ways to improve the entire wing's layout.", theme: "Creative Strategist" } },
  { id: 107, optionA: { text: "I feel best when I am the most influential person in the room.", theme: "Direct Leader" }, optionB: { text: "I feel best when everyone in the room feels heard.", theme: "Team Integrator" } },
  { id: 108, optionA: { text: "I rely on vitals and lab results to make my decisions.", theme: "Data Validator" }, optionB: { text: "I rely on my knowledge of the resident’s history.", theme: "Person-Centered" } },
  { id: 109, optionA: { text: "I love talking about where the facility will be in 5 years.", theme: "Future-Care Visionary" }, optionB: { text: "I love talking about why our values matter right now.", theme: "Mission-Driven" } },
  { id: 110, optionA: { text: "I am annoyed when people 'socialize' during med-pass.", theme: "Target-Oriented" }, optionB: { text: "I believe socializing is what makes the workday tolerable.", theme: "Morale Booster" } },
  { id: 111, optionA: { text: "I will stay late to make sure a 'good' project is 'great.'", theme: "Excellence Seeker" }, optionB: { text: "I will stay late because I feel it is my duty to finish.", theme: "Ultimate Owner" } },
  { id: 112, optionA: { text: "I prefer to work in a quiet environment.", theme: "Deep Contemplator" }, optionB: { text: "I prefer a lively environment with lots of chatter.", theme: "Staff Storyteller" } },
  { id: 113, optionA: { text: "I follow the handbook to the letter for every resident.", theme: "Standardized Care" }, optionB: { text: "I treat the handbook as a 'suggestion' during chaos.", theme: "Fluid Responder" } },
  { id: 114, optionA: { text: "I look for the root cause of an old survey deficiency.", theme: "Historical Expert" }, optionB: { text: "I look for a creative, new way to avoid the deficiency.", theme: "Creative Strategist" } },
  { id: 115, optionA: { text: "I thrive on healthy competition with other units.", theme: "Performance Driver" }, optionB: { text: "I think competition between units creates unnecessary drama.", theme: "Peace Mediator" } },
  { id: 116, optionA: { text: "I love 'collecting' different ways to handle difficult families.", theme: "Resource Collector" }, optionB: { text: "I love 'testing' new ways to handle them immediately.", theme: "Activator" } },
  { id: 117, optionA: { text: "I see the facility as one big, interconnected living system.", theme: "Holistic Thinker" }, optionB: { text: "I see the facility as a series of specific tasks and rules.", theme: "Clinical Precision" } },
  { id: 118, optionA: { text: "I can tell when a coworker is 'faking' a smile.", theme: "Compassionate Sensor" }, optionB: { text: "I don't care about their smile, as long as they do the job.", theme: "Direct Leader" } },
  { id: 119, optionA: { text: "I trust my internal judgment more than 'policy' books.", theme: "Self-Assurance" }, optionB: { text: "I trust the policy book more than my own judgment.", theme: "Risk Mitigator" } },
  { id: 120, optionA: { text: "I am excited by a new, complicated EMR software update.", theme: "Learner" }, optionB: { text: "I am excited by the chance to organize a new software launch.", theme: "Shift Coordinator" } },
  { id: 121, optionA: { text: "I come up with a hundred ideas for the holiday party.", theme: "Ideation" }, optionB: { text: "I just want to be the one who sets up the tables and chairs.", theme: "Execution" } },
  { id: 122, optionA: { text: "I notice the specific music each resident loves.", theme: "Individualization" }, optionB: { text: "I believe everyone should have access to the same music.", theme: "Consistency" } },
  { id: 123, optionA: { text: "I only trust a few people on the staff.", theme: "Relator" }, optionB: { text: "I try to make sure every new hire feels trusted and safe.", theme: "Includer" } },
  { id: 124, optionA: { text: "I want to see the budget for the new equipment.", theme: "Analytical" }, optionB: { text: "I want to be the one who gets to use the new equipment first.", theme: "Significance" } },
  { id: 125, optionA: { text: "I am the first to say 'Let's do this!' in a meeting.", theme: "Activator" }, optionB: { text: "I am the one who says 'Wait, have we thought of the risk?'", theme: "Deliberative" } },
  { id: 126, optionA: { text: "I am most proud of my 'work ethic.'", theme: "Consistent Producer" }, optionB: { text: "I am most proud of my 'clinical knowledge.'", theme: "Clinical Scholar" } },
  { id: 127, optionA: { text: "I want to be the best-known person in the facility.", theme: "Legacy Maker" }, optionB: { text: "I want to be the most trusted person by the residents.", theme: "Direct Confidant" } },
  { id: 128, optionA: { text: "I naturally focus on what could go wrong.", theme: "Risk Mitigator" }, optionB: { text: "I naturally focus on what we can win.", theme: "Performance Driver" } },
  { id: 129, optionA: { text: "I quickly see the best way through a crisis.", theme: "Pathway Mapper" }, optionB: { text: "I quickly jump into action during a crisis.", theme: "Momentum Builder" } },
  { id: 130, optionA: { text: "I advocate for the resident's personal choice.", theme: "Person-Centered" }, optionB: { text: "I advocate for the facility's safety policy.", theme: "Standardized Care" } },
  { id: 131, optionA: { text: "I enjoy telling others what needs to happen.", theme: "Direct Leader" }, optionB: { text: "I enjoy helping others figure out what needs to happen.", theme: "Staff Mentor" } },
  { id: 132, optionA: { text: "I judge a shift by the metrics (falls, med-errors).", theme: "Data Validator" }, optionB: { text: "I judge a shift by the team's energy and spirit.", theme: "Morale Booster" } },
  { id: 133, optionA: { text: "I love dreaming about 'the next big thing.'", theme: "Future-Care Visionary" }, optionB: { text: "I love preserving 'the way we've always done it.'", theme: "Historical Expert" } },
  { id: 134, optionA: { text: "I prefer to work on one complex patient chart at a time.", theme: "Target-Oriented" }, optionB: { text: "I prefer to juggle ten simple tasks at the same time.", theme: "Shift Coordinator" } },
  { id: 135, optionA: { text: "I am frustrated when people settle for 'okay' care.", theme: "Excellence Seeker" }, optionB: { text: "I am frustrated when people cause conflict.", theme: "Harmony" } },
  { id: 136, optionA: { text: "I want to understand 'why' a clinical issue happened.", theme: "Deep Contemplator" }, optionB: { text: "I want to 'fix' the clinical issue immediately.", theme: "Activator" } },
  { id: 137, optionA: { text: "I believe rules are meant to be followed strictly.", theme: "Standardized Care" }, optionB: { text: "I believe rules are meant to be adapted to the situation.", theme: "Fluid Responder" } },
  { id: 138, optionA: { text: "My work is a calling, not just a paycheck.", theme: "Mission-Driven" }, optionB: { text: "My work is about completing my tasks for the day.", theme: "Consistent Producer" } },
  { id: 139, optionA: { text: "I love coming up with new activity ideas for the residents.", theme: "Creative Strategist" }, optionB: { text: "I love finding existing ideas that worked in other facilities.", theme: "Resource Collector" } },
  { id: 140, optionA: { text: "I see how my work affects the entire healthcare system.", theme: "Holistic Thinker" }, optionB: { text: "I focus strictly on my assigned wing and my assigned tasks.", theme: "Clinical Precision" } },
  { id: 141, optionA: { text: "I am sensitive to the stress my coworkers are feeling.", theme: "Compassionate Sensor" }, optionB: { text: "I push my coworkers to hit our quality targets.", theme: "Performance Driver" } },
  { id: 142, optionA: { text: "I am confident even when the supervisor is watching.", theme: "Self-Assurance" }, optionB: { text: "I perform my best when the supervisor is watching.", theme: "Significance" } },
  { id: 143, optionA: { text: "I love watching a new CNA 'get it' for the first time.", theme: "Staff Mentor" }, optionB: { text: "I love when I am the first one to 'get it.'", theme: "Legacy Maker" } },
  { id: 144, optionA: { text: "I am known for being logical and unemotional.", theme: "Analytical" }, optionB: { text: "I am known for being caring and deeply emotional.", theme: "Compassionate Sensor" } },
  { id: 145, optionA: { text: "If a resident is unhappy, I feel it is my personal fault.", theme: "Ultimate Owner" }, optionB: { text: "If a resident is unhappy, I try to stay calm and pivot.", theme: "Fluid Responder" } },
  { id: 146, optionA: { text: "I am always looking for a new class to take.", theme: "Learner" }, optionB: { text: "I am always looking for a new goal to hit.", theme: "Target-Oriented" } },
  { id: 147, optionA: { text: "I try to make everyone feel like they belong on the team.", theme: "Includer" }, optionB: { text: "I only care if everyone is doing their job on the team.", theme: "Direct Leader" } },
  { id: 148, optionA: { text: "I am a 'firefighter'—I love fixing emergency problems.", theme: "Restorative" }, optionB: { text: "I am a 'coach'—I love making strong teams stronger.", theme: "Maximizer" } },
  { id: 149, optionA: { text: "I love discovering what makes each coworker tick.", theme: "Individualization" }, optionB: { text: "I love knowing we all share the same values.", theme: "Belief" } },
  { id: 150, optionA: { text: "I love speaking in front of a large group of staff.", theme: "Communication" }, optionB: { text: "I prefer speaking 1-on-1 with a close friend.", theme: "Direct Confidant" } },
  { id: 151, optionA: { text: "I am most proud of my 'accuracy.'", theme: "Clinical Precision" }, optionB: { text: "I am most proud of my 'efficiency.'", theme: "Consistent Producer" } },
  { id: 152, optionA: { text: "I lead by setting a powerful example.", theme: "Legacy Maker" }, optionB: { text: "I lead by building strong consensus.", theme: "Harmony" } },
  { id: 153, optionA: { text: "I prefer a plan that is 'safe.'", theme: "Risk Mitigator" }, optionB: { text: "I prefer a plan that is 'ambitious.'", theme: "Future-Care Visionary" } },
  { id: 154, optionA: { text: "I value 'clinical logic' above all else.", theme: "Data Validator" }, optionB: { text: "I value 'human connection' above all else.", theme: "Direct Confidant" } },
  { id: 155, optionA: { text: "I am at my best when I am 'the boss.'", theme: "Direct Leader" }, optionB: { text: "I am at my best when I am 'the expert.'", theme: "Clinical Scholar" } },
  { id: 156, optionA: { text: "I prioritize 'the many' (the whole team).", theme: "Team Integrator" }, optionB: { text: "I prioritize 'the one' (the individual).", theme: "Person-Centered" } },
  { id: 157, optionA: { text: "I love the 'start' of a new project.", theme: "Momentum Builder" }, optionB: { text: "I love the 'finish' of a long project.", theme: "Target-Oriented" } },
  { id: 158, optionA: { text: "I am driven by 'what could be.'", theme: "Creative Strategist" }, optionB: { text: "I am driven by 'what is proven.'", theme: "Historical Expert" } },
  { id: 159, optionA: { text: "I find joy in 'fixing' people’s problems.", theme: "Restorative" }, optionB: { text: "I find joy in 'improving' people’s talents.", theme: "Staff Mentor" } },
  { id: 160, optionA: { text: "I rely on my 'preparation.'", theme: "Deliberative" }, optionB: { text: "I rely on my 'instincts.'", theme: "Self-Assurance" } },
  { id: 161, optionA: { text: "I want to be 'respected.'", theme: "Significance" }, optionB: { text: "I want to be 'liked.'", theme: "Positivity" } },
  { id: 162, optionA: { text: "I focus on the 'clinical outcome.'", theme: "Performance Driver" }, optionB: { text: "I focus on the 'resident experience.'", theme: "Holistic Thinker" } },
  { id: 163, optionA: { text: "I am a 'logical' problem solver.", theme: "Analytical" }, optionB: { text: "I am an 'intuitive' problem solver.", theme: "Ideation" } },
  { id: 164, optionA: { text: "I keep my work life and personal life separate.", theme: "Focus" }, optionB: { text: "I blend my work and personal relationships.", theme: "Relator" } },
  { id: 165, optionA: { text: "I am motivated by 'internal values.'", theme: "Mission-Driven" }, optionB: { text: "I am motivated by 'external goals.'", theme: "Consistent Producer" } },
  { id: 166, optionA: { text: "I enjoy 'managing' the schedule.", theme: "Shift Coordinator" }, optionB: { text: "I enjoy 'executing' the schedule.", theme: "Discipline" } },
  { id: 167, optionA: { text: "I am the first to speak in a group.", theme: "Communication" }, optionB: { text: "I am the last to speak in a group.", theme: "Deep Contemplator" } },
  { id: 168, optionA: { text: "I want to change the 'entire system.'", theme: "Strategic" }, optionB: { text: "I want to change 'one life at a time.'", theme: "Empathy" } },
  { id: 169, optionA: { text: "I am a 'specialist' in one area.", theme: "Learner" }, optionB: { text: "I am a 'generalist' who can do it all.", theme: "Adaptability" } },
  { id: 170, optionA: { text: "I value 'transparency' and truth.", theme: "Command" }, optionB: { text: "I value 'kindness' and diplomacy.", theme: "Harmony" } },
  { id: 171, optionA: { text: "I am energized by 'new faces.'", theme: "Community Connector" }, optionB: { text: "I am energized by 'familiar faces.'", theme: "Direct Confidant" } },
  { id: 172, optionA: { text: "I need 'all the details' before I start.", theme: "Input" }, optionB: { text: "I just need 'the main goal' before I start.", theme: "Activator" } },
  { id: 173, optionA: { text: "I want to be the 'fastest' worker.", theme: "Competition" }, optionB: { text: "I want to be the 'most reliable' worker.", theme: "Responsibility" } },
  { id: 174, optionA: { text: "I see 'patterns' in the data.", theme: "Analytical" }, optionB: { text: "I see 'stories' in the data.", theme: "Staff Storyteller" } },
  { id: 175, optionA: { text: "I am a 'serious' and focused worker.", theme: "Target-Oriented" }, optionB: { text: "I am a 'fun' and energetic worker.", theme: "Morale Booster" } },
  { id: 176, optionA: { text: "I hate 'wasted time.'", theme: "Focus" }, optionB: { text: "I hate 'unnecessary conflict.'", theme: "Includer" } },
  { id: 177, optionA: { text: "I am defined by 'my results.'", theme: "Consistent Producer" }, optionB: { text: "I am defined by 'my relationships.'", theme: "Team Integrator" } }
];